version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    # restart: unless-stopped
    volumes:
      - ./client:/client
    environment:
      - NODE_ENV=development
    command: [ "npm", "start" ]
  api:
    build: ./api
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./api:/api

  mysql:
    image: arm64v8/mysql:oracle
    # restart: unless-stopped
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/:ro
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  proxy:
    build: ./proxy
    links:
      - api
      - client
      - phpmyadmin
    ports:
      - 80:80

volumes:
  db: {}
