version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    environment:
      - NODE_ENV=development
    command: [ "npm", "start" ]
  api:
    build: ./api
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./api:/api
  proxy:
    build: ./proxy
    links:
      - api
      - client
      # - phpmyadmin
    ports:
      - 80:80
